In [41]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.9.0-py3-none-any.whl.metadata (15 kB)
Collecting alembic>=1.5.0 (from optuna)
  Downloading alembic-1.18.5-py3-none-any.whl.metadata (7.2 kB)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.51)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna) (1.1.3)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.5.2)
Downloading optuna-4.9.0-py3-none-any.whl (425 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 425.6/425.6 kB 7.3 MB/s eta 0:00:00
Downloading alembic-1.18.5-py3-none-any.whl (264 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 264.7/264.7 kB 18.1 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, alembic, optuna
Successfully installed alembic-1.18.5 colorlog-6.10.1 optuna-4.9.0

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression

In [2]:
#prepare the data
df = pd.read_csv('/content/cancer-risk-factors.csv')

In [3]:
df.head(5)

,Patient_ID,Cancer_Type,Age,Gender,Smoking,Alcohol_Use,Obesity,Family_History,Diet_Red_Meat,Diet_Salted_Processed,...,Physical_Activity,Air_Pollution,Occupational_Hazards,BRCA_Mutation,H_Pylori_Infection,Calcium_Intake,Overall_Risk_Score,BMI,Physical_Activity_Level,Risk_Level
0,LU0000,Breast,68,0,7,2,8,0,5,3,...,4,6,3,1,0,0,0.398696,28.0,5,Medium
1,LU0001,Prostate,74,1,8,9,8,0,0,3,...,1,3,3,0,0,5,0.424299,25.4,9,Medium
2,LU0002,Skin,55,1,7,10,7,0,3,3,...,1,8,10,0,0,6,0.605082,28.6,2,Medium
3,LU0003,Colon,61,0,6,2,2,0,6,2,...,6,4,8,0,0,8,0.318449,32.1,7,Low
4,LU0004,Lung,67,1,10,7,4,0,6,3,...,9,10,9,0,0,5,0.524358,25.1,2,Medium

In [9]:
x = df.drop(columns=['Risk_Level','Patient_ID', 'Cancer_Type'])

# Encode the target variable
le = LabelEncoder()
y = le.fit_transform(df['Risk_Level'])

In [10]:
x

,Age,Gender,Smoking,Alcohol_Use,Obesity,Family_History,Diet_Red_Meat,Diet_Salted_Processed,Fruit_Veg_Intake,Physical_Activity,Air_Pollution,Occupational_Hazards,BRCA_Mutation,H_Pylori_Infection,Calcium_Intake,Overall_Risk_Score,BMI,Physical_Activity_Level
0,68,0,7,2,8,0,5,3,7,4,6,3,1,0,0,0.398696,28.0,5
1,74,1,8,9,8,0,0,3,7,1,3,3,0,0,5,0.424299,25.4,9
2,55,1,7,10,7,0,3,3,4,1,8,10,0,0,6,0.605082,28.6,2
3,61,0,6,2,2,0,6,2,4,6,4,8,0,0,8,0.318449,32.1,7
4,67,1,10,7,4,0,6,3,10,9,10,9,0,0,5,0.524358,25.1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,60,1,4,6,4,0,10,6,4,4,5,3,1,0,4,0.437539,30.3,3
1996,84,1,5,7,8,0,10,0,1,2,1,3,0,0,2,0.451128,25.9,4
1997,65,0,7,2,10,0,4,2,2,3,6,0,0,1,0,0.295760,22.5,3
1998,64,1,10,2,10,0,2,10,7,5,4,2,0,0,10,0.422201,25.3,3
1999,64,0,3,4,10,0,0,5,1,0,3,9,0,0,0,0.518137,23.0,3

In [6]:
y

array([2, 2, 2, ..., 1, 2, 2])

## why cancer_type was removed from the features list

- It's not a predictive input - it's an outcome label or categorical grouping that's already strongly correlated with Risk Level

- If we include it, the model will cheat by learning the mapping like Prostate --> High risk, instead of learning from true risk factors (smoking, BMI etc)

In [11]:
# Split into training/test

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42, stratify=y)

In [12]:
# Feature Scaling

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [14]:
#model
model = RandomForestClassifier(random_state=42, n_estimators=100)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [15]:
y_pred = model.predict(X_test)

print("Classification Report")
print(classification_report(y_test, y_pred, target_names=le.classes_))

print("Confusion Matrix")
print(confusion_matrix(y_test, y_pred))

Classification Report
              precision    recall  f1-score   support

        High       1.00      0.95      0.97        20
         Low       1.00      1.00      1.00        65
      Medium       1.00      1.00      1.00       315

    accuracy                           1.00       400
   macro avg       1.00      0.98      0.99       400
weighted avg       1.00      1.00      1.00       400

Confusion Matrix
[[ 19   0   1]
 [  0  65   0]
 [  0   0 315]]

The model accurately distinguishes all risk levels, with only 1 mistake out of 400 with imbalanced dataset. that means it has an overfitting problem

##Logistic Regression

In [16]:
log_reg = LogisticRegression(random_state=42)
log_reg.fit(X_train, y_train)

LogisticRegression(random_state=42)

In [18]:
y_pred_lr = log_reg.predict(X_test)

print("Classification Report")
print(classification_report(y_test, y_pred_lr, target_names=le.classes_))

print("Confusion Matrix")
print(confusion_matrix(y_test, y_pred_lr))

Classification Report
              precision    recall  f1-score   support

        High       1.00      0.80      0.89        20
         Low       0.97      0.95      0.96        65
      Medium       0.98      0.99      0.99       315

    accuracy                           0.98       400
   macro avg       0.98      0.92      0.95       400
weighted avg       0.98      0.98      0.98       400

Confusion Matrix
[[ 16   0   4]
 [  0  62   3]
 [  0   2 313]]

## Removing Overall_Risk_Score and retrying

In [19]:
X_new = df.drop(columns=['Risk_Level','Patient_ID', 'Cancer_Type', 'Overall_Risk_Score'])

# Encode the target variable
le_new = LabelEncoder()
y_new = le_new.fit_transform(df['Risk_Level'])

In [20]:
# Split into training/test

X_train_new, X_test_new, y_train_new, y_test_new = train_test_split(X_new, y_new, test_size = 0.2, random_state=42, stratify=y)

In [21]:
# Feature Scaling

scaler_new = StandardScaler()
X_train_new = scaler_new.fit_transform(X_train_new)
X_test_new = scaler_new.transform(X_test_new)

In [22]:
model_new = RandomForestClassifier(random_state=42, n_estimators=100)
model_new.fit(X_train_new, y_train_new)

RandomForestClassifier(random_state=42)

In [23]:
y_pred_new = model_new.predict(X_test_new)

print("Classification Report")
print(classification_report(y_test_new, y_pred_new, target_names=le.classes_))

print("Confusion Matrix")
print(confusion_matrix(y_test_new, y_pred_new))

Classification Report
              precision    recall  f1-score   support

        High       1.00      0.05      0.10        20
         Low       0.85      0.34      0.48        65
      Medium       0.83      0.99      0.90       315

    accuracy                           0.83       400
   macro avg       0.89      0.46      0.49       400
weighted avg       0.84      0.83      0.80       400

Confusion Matrix
[[  1   0  19]
 [  0  22  43]
 [  0   4 311]]

In [24]:
df.Risk_Level.value_counts()

Risk_Level
Medium    1574
Low        324
High       102
Name: count, dtype: int64

## SMOTE - Synthetic Minority Over-Sampling Technique

In [31]:
X = df.drop(columns=['Risk_Level','Patient_ID', 'Cancer_Type', 'Overall_Risk_Score'])
y = df['Risk_Level']

In [32]:
# Split into training/test

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42, stratify=y)

In [35]:
from imblearn.over_sampling import SMOTE

In [37]:
smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train,y_train)

print("Class Distribution")
print(pd.Series(y_train_res).value_counts())

Class Distribution
Risk_Level
Medium    1259
Low       1259
High      1259
Name: count, dtype: int64

In [38]:
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train_res, y_train_res)

RandomForestClassifier(random_state=42)

In [40]:
y_pred_2 = rf_model.predict(X_test)

print("Classification Report")
print(classification_report(y_test, y_pred))

print("Confusion Matrix")
print(confusion_matrix(y_test, y_pred_2))

Classification Report
              precision    recall  f1-score   support

        High       0.41      0.35      0.38        20
         Low       0.73      0.58      0.65        65
      Medium       0.88      0.92      0.90       315

    accuracy                           0.84       400
   macro avg       0.67      0.62      0.64       400
weighted avg       0.83      0.84      0.83       400

Confusion Matrix
[[  7   0  13]
 [  0  38  27]
 [ 10  14 291]]

- Accuracy: 84%
- High Risk: 7 correctly classified, 13 mis-classified as Medium
- Low Risk: 38 correctly classified, 27 confused with Medium
- Medium Risk: 291 correctly classified, 24 confused as High/Low

- Still struggles to detect High-risk patients even with SMOTE

## Optuna Tuning

In [43]:
# Optuna tuning
import optuna
from optuna.samplers import TPESampler
from sklearn.metrics import classification_report, confusion_matrix, make_scorer, f1_score
from sklearn.model_selection import StratifiedKFold, cross_val_score

import numpy as np
import joblib  # optional, to save model/study

In [44]:
X_train_res.shape

(3777, 17)

In [45]:
from sklearn.metrics import f1_score, make_scorer

# Define macro F1 scorer explicitly for multiclass
def macro_f1(y_true, y_pred):
    return f1_score(y_true, y_pred, average='macro')

scorer = make_scorer(macro_f1)

In [46]:
def objective(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 50, 500),
        'max_depth': trial.suggest_int('max_depth', 3, 30),
        'min_samples_split': trial.suggest_int('min_samples_split', 2, 10),
        'min_samples_leaf': trial.suggest_int('min_samples_leaf', 1, 10),
        'max_features': trial.suggest_categorical('max_features', ['sqrt', 'log2']),
        'bootstrap': trial.suggest_categorical('bootstrap', [True, False]),
        'criterion': trial.suggest_categorical('criterion', ['gini', 'entropy']),
        'random_state': 42,
        'n_jobs': -1
    }

    model = RandomForestClassifier(**params)

    cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)
    scores = []

    for train_idx, val_idx in cv.split(X_train_res, y_train_res):
        X_t, X_v = X_train_res.iloc[train_idx], X_train_res.iloc[val_idx]
        y_t, y_v = y_train_res.iloc[train_idx], y_train_res.iloc[val_idx]

        model.fit(X_t, y_t)
        y_pred = model.predict(X_v)

        score = f1_score(y_v, y_pred, average='macro')  # explicit multiclass handling
        scores.append(score)

    return np.mean(scores)

In [47]:
# --- Create study ---
sampler = TPESampler(seed=42)
study = optuna.create_study(direction='maximize', sampler=sampler, study_name='rf_macro_f1')

[I 2026-07-09 09:09:21,933] A new study created in memory with name: rf_macro_f1

In [48]:
# --- Run optimization ---
n_trials = 50  # change to 100+ if you want more thorough search
study.optimize(objective, n_trials=n_trials, show_progress_bar=True)

print("Best trial:")
print("  Value (macro F1):", study.best_value)
print("  Params:")
for k, v in study.best_params.items():
    print(f"    {k}: {v}")

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-07-09 09:09:30,646] Trial 0 finished with value: 0.9402356457892479 and parameters: {'n_estimators': 218, 'max_depth': 29, 'min_samples_split': 8, 'min_samples_leaf': 6, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 0 with value: 0.9402356457892479.
[I 2026-07-09 09:09:32,137] Trial 1 finished with value: 0.9488676606640238 and parameters: {'n_estimators': 59, 'max_depth': 30, 'min_samples_split': 9, 'min_samples_leaf': 3, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 1 with value: 0.9488676606640238.
[I 2026-07-09 09:09:35,777] Trial 2 finished with value: 0.9045887437906642 and parameters: {'n_estimators': 325, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 1 with value: 0.9488676606640238.
[I 2026-07-09 09:09:39,532] Trial 3 finished with value: 0.9089885645353499 and parameters: {'n_estimators': 324, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 10, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 1 with value: 0.9488676606640238.
[I 2026-07-09 09:09:41,109] Trial 4 finished with value: 0.9266627124403138 and parameters: {'n_estimators': 105, 'max_depth': 16, 'min_samples_split': 2, 'min_samples_leaf': 10, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 1 with value: 0.9488676606640238.
[I 2026-07-09 09:09:55,925] Trial 5 finished with value: 0.9319302481500912 and parameters: {'n_estimators': 487, 'max_depth': 24, 'min_samples_split': 10, 'min_samples_leaf': 9, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 1 with value: 0.9488676606640238.
[I 2026-07-09 09:10:05,019] Trial 6 finished with value: 0.9427963195232238 and parameters: {'n_estimators': 225, 'max_depth': 10, 'min_samples_split': 9, 'min_samples_leaf': 4, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 1 with value: 0.9488676606640238.
[I 2026-07-09 09:10:13,179] Trial 7 finished with value: 0.9123217127530691 and parameters: {'n_estimators': 398, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 9, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 1 with value: 0.9488676606640238.
[I 2026-07-09 09:10:19,667] Trial 8 finished with value: 0.9536461969280231 and parameters: {'n_estimators': 439, 'max_depth': 20, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 8 with value: 0.9536461969280231.
[I 2026-07-09 09:10:21,165] Trial 9 finished with value: 0.9302234411015569 and parameters: {'n_estimators': 103, 'max_depth': 22, 'min_samples_split': 8, 'min_samples_leaf': 6, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 8 with value: 0.9536461969280231.
[I 2026-07-09 09:10:29,736] Trial 10 finished with value: 0.9533838105385382 and parameters: {'n_estimators': 487, 'max_depth': 16, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 8 with value: 0.9536461969280231.
[I 2026-07-09 09:10:37,892] Trial 11 finished with value: 0.9536505757542448 and parameters: {'n_estimators': 492, 'max_depth': 16, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 11 with value: 0.9536505757542448.
[I 2026-07-09 09:10:44,576] Trial 12 finished with value: 0.9531299794733039 and parameters: {'n_estimators': 417, 'max_depth': 17, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 11 with value: 0.9536505757542448.
[I 2026-07-09 09:10:51,904] Trial 13 finished with value: 0.9493575585121518 and parameters: {'n_estimators': 421, 'max_depth': 20, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 11 with value: 0.9536505757542448.
[I 2026-07-09 09:11:06,522] Trial 14 finished with value: 0.9509195904585312 and parameters: {'n_estimators': 496, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 11 with value: 0.9536505757542448.
[I 2026-07-09 09:11:12,609] Trial 15 finished with value: 0.8013295571346774 and parameters: {'n_estimators': 359, 'max_depth': 3, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 11 with value: 0.9536505757542448.
[I 2026-07-09 09:11:20,349] Trial 16 finished with value: 0.9500929711020928 and parameters: {'n_estimators': 439, 'max_depth': 25, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 11 with value: 0.9536505757542448.
[I 2026-07-09 09:11:24,022] Trial 17 finished with value: 0.9490553696128279 and parameters: {'n_estimators': 252, 'max_depth': 14, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 11 with value: 0.9536505757542448.
[I 2026-07-09 09:11:31,529] Trial 18 finished with value: 0.9347249447188308 and parameters: {'n_estimators': 452, 'max_depth': 19, 'min_samples_split': 6, 'min_samples_leaf': 5, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 11 with value: 0.9536505757542448.
[I 2026-07-09 09:11:37,491] Trial 19 finished with value: 0.9434643830349606 and parameters: {'n_estimators': 370, 'max_depth': 27, 'min_samples_split': 7, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 11 with value: 0.9536505757542448.
[I 2026-07-09 09:11:42,141] Trial 20 finished with value: 0.9538572473881702 and parameters: {'n_estimators': 308, 'max_depth': 21, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 20 with value: 0.9538572473881702.
[I 2026-07-09 09:11:47,682] Trial 21 finished with value: 0.9535876178112517 and parameters: {'n_estimators': 276, 'max_depth': 21, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 20 with value: 0.9538572473881702.
[I 2026-07-09 09:11:50,434] Trial 22 finished with value: 0.9495371008841164 and parameters: {'n_estimators': 185, 'max_depth': 18, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 20 with value: 0.9538572473881702.
[I 2026-07-09 09:11:55,102] Trial 23 finished with value: 0.9531092017699317 and parameters: {'n_estimators': 313, 'max_depth': 14, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 20 with value: 0.9538572473881702.
[I 2026-07-09 09:12:03,118] Trial 24 finished with value: 0.9490577908212461 and parameters: {'n_estimators': 454, 'max_depth': 24, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 20 with value: 0.9538572473881702.
[I 2026-07-09 09:12:08,557] Trial 25 finished with value: 0.9439626387411238 and parameters: {'n_estimators': 379, 'max_depth': 22, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 20 with value: 0.9538572473881702.
[I 2026-07-09 09:12:12,724] Trial 26 finished with value: 0.9513765641515987 and parameters: {'n_estimators': 176, 'max_depth': 14, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 20 with value: 0.9538572473881702.
[I 2026-07-09 09:12:19,171] Trial 27 finished with value: 0.9391200251595914 and parameters: {'n_estimators': 463, 'max_depth': 26, 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 20 with value: 0.9538572473881702.
[I 2026-07-09 09:12:24,283] Trial 28 finished with value: 0.9458937449513164 and parameters: {'n_estimators': 297, 'max_depth': 20, 'min_samples_split': 7, 'min_samples_leaf': 2, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 20 with value: 0.9538572473881702.
[I 2026-07-09 09:12:31,053] Trial 29 finished with value: 0.9380823175174848 and parameters: {'n_estimators': 392, 'max_depth': 28, 'min_samples_split': 3, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 20 with value: 0.9538572473881702.
[I 2026-07-09 09:12:36,387] Trial 30 finished with value: 0.9514364148941566 and parameters: {'n_estimators': 353, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 20 with value: 0.9538572473881702.
[I 2026-07-09 09:12:42,041] Trial 31 finished with value: 0.9538651347523951 and parameters: {'n_estimators': 268, 'max_depth': 22, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 31 with value: 0.9538651347523951.
[I 2026-07-09 09:12:45,851] Trial 32 finished with value: 0.9506245532302523 and parameters: {'n_estimators': 258, 'max_depth': 18, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 31 with value: 0.9538651347523951.
[I 2026-07-09 09:12:48,992] Trial 33 finished with value: 0.9536151872087492 and parameters: {'n_estimators': 204, 'max_depth': 22, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 31 with value: 0.9538651347523951.
[I 2026-07-09 09:12:55,940] Trial 34 finished with value: 0.9526129721370902 and parameters: {'n_estimators': 336, 'max_depth': 23, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 31 with value: 0.9538651347523951.
[I 2026-07-09 09:12:58,373] Trial 35 finished with value: 0.9492661271084047 and parameters: {'n_estimators': 160, 'max_depth': 16, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 31 with value: 0.9538651347523951.
[I 2026-07-09 09:13:03,276] Trial 36 finished with value: 0.9523420854192387 and parameters: {'n_estimators': 270, 'max_depth': 30, 'min_samples_split': 4, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 31 with value: 0.9538651347523951.
[I 2026-07-09 09:13:07,773] Trial 37 finished with value: 0.9533157806991763 and parameters: {'n_estimators': 234, 'max_depth': 20, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 31 with value: 0.9538651347523951.
[I 2026-07-09 09:13:10,287] Trial 38 finished with value: 0.9544392962666621 and parameters: {'n_estimators': 138, 'max_depth': 19, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 38 with value: 0.9544392962666621.
[I 2026-07-09 09:13:11,509] Trial 39 finished with value: 0.9467135974780031 and parameters: {'n_estimators': 67, 'max_depth': 18, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 38 with value: 0.9544392962666621.
[I 2026-07-09 09:13:13,724] Trial 40 finished with value: 0.9520145123524558 and parameters: {'n_estimators': 124, 'max_depth': 25, 'min_samples_split': 2, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 38 with value: 0.9544392962666621.
[I 2026-07-09 09:13:23,914] Trial 41 finished with value: 0.9560631132856403 and parameters: {'n_estimators': 471, 'max_depth': 21, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 41 with value: 0.9560631132856403.
[I 2026-07-09 09:13:26,880] Trial 42 finished with value: 0.9544291480769722 and parameters: {'n_estimators': 140, 'max_depth': 21, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 41 with value: 0.9560631132856403.
[I 2026-07-09 09:13:30,087] Trial 43 finished with value: 0.9549891743614697 and parameters: {'n_estimators': 147, 'max_depth': 23, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 41 with value: 0.9560631132856403.
[I 2026-07-09 09:13:33,634] Trial 44 finished with value: 0.9555018892187821 and parameters: {'n_estimators': 139, 'max_depth': 23, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 41 with value: 0.9560631132856403.
[I 2026-07-09 09:13:35,979] Trial 45 finished with value: 0.9474979644823619 and parameters: {'n_estimators': 136, 'max_depth': 24, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 41 with value: 0.9560631132856403.
[I 2026-07-09 09:13:37,440] Trial 46 finished with value: 0.9466633204688814 and parameters: {'n_estimators': 81, 'max_depth': 23, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 41 with value: 0.9560631132856403.
[I 2026-07-09 09:13:40,111] Trial 47 finished with value: 0.9549728495083506 and parameters: {'n_estimators': 144, 'max_depth': 28, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 41 with value: 0.9560631132856403.
[I 2026-07-09 09:13:41,989] Trial 48 finished with value: 0.9522723907962517 and parameters: {'n_estimators': 105, 'max_depth': 29, 'min_samples_split': 2, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 41 with value: 0.9560631132856403.
[I 2026-07-09 09:13:43,387] Trial 49 finished with value: 0.9428647277991624 and parameters: {'n_estimators': 51, 'max_depth': 27, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 41 with value: 0.9560631132856403.
Best trial:
  Value (macro F1): 0.9560631132856403
  Params:
    n_estimators: 471
    max_depth: 21
    min_samples_split: 3
    min_samples_leaf: 2
    max_features: sqrt
    bootstrap: False
    criterion: entropy

In [49]:
# Train final model with best params and full training data, then evaluate on test
best_params = {
    'n_estimators': 347,
    'max_depth': 19,
    'min_samples_split': 2,
    'min_samples_leaf': 1,
    'max_features': 'sqrt',
    'bootstrap': False,
    'criterion': 'gini',
    'random_state': 42,
    'n_jobs': -1
}


final_rf = RandomForestClassifier(**best_params)
final_rf.fit(X_train_res, y_train_res)         # resampled training set
y_pred_test = final_rf.predict(X_test)        # untouched test set

from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, y_pred_test))
print(confusion_matrix(y_test, y_pred_test))

              precision    recall  f1-score   support

        High       0.36      0.25      0.29        20
         Low       0.72      0.58      0.64        65
      Medium       0.87      0.92      0.90       315

    accuracy                           0.83       400
   macro avg       0.65      0.59      0.61       400
weighted avg       0.82      0.83      0.83       400

[[  5   0  15]
 [  0  38  27]
 [  9  15 291]]

## ACCURACY IS 84%

In [51]:
from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.metrics import f1_score, make_scorer, recall_score
import optuna
import numpy as np

# scorer (macro f1)
def macro_f1(y_true, y_pred):
    return f1_score(y_true, y_pred, average='macro')

macro_f1_scorer = make_scorer(macro_f1)

def objective(trial):
    # RF params to try
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 100, 400),
        'max_depth': trial.suggest_int('max_depth', 6, 20),
        'min_samples_split': trial.suggest_int('min_samples_split', 2, 8),
        'min_samples_leaf': trial.suggest_int('min_samples_leaf', 1, 6),
        'max_features': trial.suggest_categorical('max_features', ['sqrt','log2']),
        'bootstrap': trial.suggest_categorical('bootstrap', [True, False]),
        'criterion': trial.suggest_categorical('criterion', ['gini','entropy']),
        'random_state': 42,
        'n_jobs': 1   # avoid nested parallelism inside cross_val_score
    }

    sm = SMOTE(random_state=42)
    rf = RandomForestClassifier(**params)
    pipe = ImbPipeline([('smote', sm), ('rf', rf)])

    cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)
    scores = cross_val_score(pipe, X_train, y_train, cv=cv, scoring=macro_f1_scorer, n_jobs=1)
    return float(np.mean(scores))

study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler(seed=42))
study.optimize(objective, n_trials=30)
print(study.best_value, study.best_params)

[I 2026-07-09 09:31:15,929] A new study created in memory with name: no-name-1add78dd-568b-4a5f-bc90-a03b61fbcda2
[I 2026-07-09 09:31:23,484] Trial 0 finished with value: 0.671473898202647 and parameters: {'n_estimators': 212, 'max_depth': 20, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 0 with value: 0.671473898202647.
[I 2026-07-09 09:31:25,561] Trial 1 finished with value: 0.6657242146375855 and parameters: {'n_estimators': 106, 'max_depth': 20, 'min_samples_split': 7, 'min_samples_leaf': 2, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 0 with value: 0.671473898202647.
[I 2026-07-09 09:31:32,064] Trial 2 finished with value: 0.6616028068735651 and parameters: {'n_estimators': 284, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 3, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 0 with value: 0.671473898202647.
[I 2026-07-09 09:31:38,473] Trial 3 finished with value: 0.6822470358393412 and parameters: {'n_estimators': 282, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 6, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 3 with value: 0.6822470358393412.
[I 2026-07-09 09:31:41,749] Trial 4 finished with value: 0.6843940052187558 and parameters: {'n_estimators': 136, 'max_depth': 13, 'min_samples_split': 2, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 4 with value: 0.6843940052187558.
[I 2026-07-09 09:31:55,498] Trial 5 finished with value: 0.6766106997681756 and parameters: {'n_estimators': 391, 'max_depth': 17, 'min_samples_split': 8, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 4 with value: 0.6843940052187558.
[I 2026-07-09 09:32:02,139] Trial 6 finished with value: 0.6736420648931846 and parameters: {'n_estimators': 216, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 3, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 4 with value: 0.6843940052187558.
[I 2026-07-09 09:32:06,380] Trial 7 finished with value: 0.6740912674902791 and parameters: {'n_estimators': 332, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 4 with value: 0.6843940052187558.
[I 2026-07-09 09:32:13,210] Trial 8 finished with value: 0.6725157701607243 and parameters: {'n_estimators': 359, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 4 with value: 0.6843940052187558.
[I 2026-07-09 09:32:15,351] Trial 9 finished with value: 0.6844259490685912 and parameters: {'n_estimators': 135, 'max_depth': 16, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 9 with value: 0.6844259490685912.
[I 2026-07-09 09:32:18,355] Trial 10 finished with value: 0.67605179333866 and parameters: {'n_estimators': 180, 'max_depth': 13, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 9 with value: 0.6844259490685912.
[I 2026-07-09 09:32:19,941] Trial 11 finished with value: 0.6891788196764784 and parameters: {'n_estimators': 102, 'max_depth': 13, 'min_samples_split': 5, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 11 with value: 0.6891788196764784.
[I 2026-07-09 09:32:22,510] Trial 12 finished with value: 0.685885171078045 and parameters: {'n_estimators': 146, 'max_depth': 16, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 11 with value: 0.6891788196764784.
[I 2026-07-09 09:32:25,036] Trial 13 finished with value: 0.682259362370039 and parameters: {'n_estimators': 103, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 11 with value: 0.6891788196764784.
[I 2026-07-09 09:32:27,663] Trial 14 finished with value: 0.6867574709319834 and parameters: {'n_estimators': 173, 'max_depth': 17, 'min_samples_split': 5, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 11 with value: 0.6891788196764784.
[I 2026-07-09 09:32:30,611] Trial 15 finished with value: 0.6876263247871423 and parameters: {'n_estimators': 193, 'max_depth': 18, 'min_samples_split': 4, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 11 with value: 0.6891788196764784.
[I 2026-07-09 09:32:34,263] Trial 16 finished with value: 0.6829292695654766 and parameters: {'n_estimators': 244, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 11 with value: 0.6891788196764784.
[I 2026-07-09 09:32:38,182] Trial 17 finished with value: 0.6886016946825652 and parameters: {'n_estimators': 183, 'max_depth': 18, 'min_samples_split': 3, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 11 with value: 0.6891788196764784.
[I 2026-07-09 09:32:44,284] Trial 18 finished with value: 0.6876658746508867 and parameters: {'n_estimators': 256, 'max_depth': 15, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 11 with value: 0.6891788196764784.
[I 2026-07-09 09:32:46,894] Trial 19 finished with value: 0.6464387889366338 and parameters: {'n_estimators': 157, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 11 with value: 0.6891788196764784.
[I 2026-07-09 09:32:52,210] Trial 20 finished with value: 0.6843336808415691 and parameters: {'n_estimators': 121, 'max_depth': 19, 'min_samples_split': 6, 'min_samples_leaf': 6, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 11 with value: 0.6891788196764784.
[I 2026-07-09 09:32:59,285] Trial 21 finished with value: 0.6850399771430072 and parameters: {'n_estimators': 250, 'max_depth': 14, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 11 with value: 0.6891788196764784.
[I 2026-07-09 09:33:08,188] Trial 22 finished with value: 0.6858943971433339 and parameters: {'n_estimators': 303, 'max_depth': 15, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 11 with value: 0.6891788196764784.
[I 2026-07-09 09:33:13,877] Trial 23 finished with value: 0.6880679266769242 and parameters: {'n_estimators': 230, 'max_depth': 18, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 11 with value: 0.6891788196764784.
[I 2026-07-09 09:33:18,389] Trial 24 finished with value: 0.686256860224416 and parameters: {'n_estimators': 220, 'max_depth': 18, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 11 with value: 0.6891788196764784.
[I 2026-07-09 09:33:21,685] Trial 25 finished with value: 0.6888087579398032 and parameters: {'n_estimators': 195, 'max_depth': 18, 'min_samples_split': 3, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 11 with value: 0.6891788196764784.
[I 2026-07-09 09:33:24,855] Trial 26 finished with value: 0.6829451833023922 and parameters: {'n_estimators': 198, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 11 with value: 0.6891788196764784.
[I 2026-07-09 09:33:29,397] Trial 27 finished with value: 0.6873144830836077 and parameters: {'n_estimators': 172, 'max_depth': 19, 'min_samples_split': 6, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 11 with value: 0.6891788196764784.
[I 2026-07-09 09:33:36,907] Trial 28 finished with value: 0.6920459973061482 and parameters: {'n_estimators': 155, 'max_depth': 17, 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 28 with value: 0.6920459973061482.
[I 2026-07-09 09:33:42,346] Trial 29 finished with value: 0.6788032712260076 and parameters: {'n_estimators': 156, 'max_depth': 20, 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 28 with value: 0.6920459973061482.

0.6920459973061482 {'n_estimators': 155, 'max_depth': 17, 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}

In [52]:
# Suppose best_params from study:
best = study.best_params
rf = RandomForestClassifier(**best, random_state=42, n_jobs=-1)

pipe_final = ImbPipeline([('smote', SMOTE(random_state=42)), ('rf', rf)])
pipe_final.fit(X_train, y_train)   # fit on original X_train (pipeline will SMOTE inside)

y_test_pred = pipe_final.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, y_test_pred))
print(confusion_matrix(y_test, y_test_pred))

              precision    recall  f1-score   support

        High       0.38      0.40      0.39        20
         Low       0.70      0.60      0.64        65
      Medium       0.88      0.90      0.89       315

    accuracy                           0.83       400
   macro avg       0.65      0.63      0.64       400
weighted avg       0.83      0.83      0.83       400

[[  8   0  12]
 [  0  39  26]
 [ 13  17 285]]

## XGBOOST

In [53]:
# baseline XGBoost (SMOTE inside pipeline - no leakage)

from xgboost import XGBClassifier
from imblearn.pipeline import Pipeline as ImbPipeline

le = LabelEncoder()
le.fit(y_train)

y_train_enc = le.transform(y_train)
y_test_enc = le.transform(y_test)

# Build Pipeline
xgb = XGBClassifier(use_label_encoder=False, eval_metrics='mlogloss', random_state=42, n_jobs=-1)
pipe = ImbPipeline([
    ('smote', SMOTE(random_state=42)),
    ('xgb', xgb)
])

pipe.fit(X_train, y_train_enc)

y_pred_enc = pipe.predict(X_test)

y_pred = le.inverse_transform(y_pred_enc)
y_test_orig = le.inverse_transform(y_test_enc)

print("Baseline XGB Classifier")
print(classification_report(y_test_orig, y_pred))
print("Confusion Matrix")
print(confusion_matrix(y_test_orig, y_pred))

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:42:14] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "eval_metrics", "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

Baseline XGB Classifier
              precision    recall  f1-score   support

        High       0.35      0.40      0.37        20
         Low       0.77      0.71      0.74        65
      Medium       0.90      0.91      0.91       315

    accuracy                           0.85       400
   macro avg       0.67      0.67      0.67       400
weighted avg       0.85      0.85      0.85       400

Confusion Matrix
[[  8   0  12]
 [  0  46  19]
 [ 15  14 286]]

In [55]:
## Optuna + XGBoost pipeline that optimizes recall for the High class.

# --- Imports ---
import optuna
from optuna.samplers import TPESampler
from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.over_sampling import SMOTE
from xgboost import XGBClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import recall_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder
import numpy as np

# --- Settings ---
TARGET_LABEL = 'High'       # label whose recall we want to maximize
LABEL_ORDER = ['High', 'Low', 'Medium']  # must match your label names exactly
N_TRIALS = 40               # start with 40; increase to 100+ for more thorough search
CV_FOLDS = 3

# --- Encode labels once (keep mapping stable) ---
le = LabelEncoder()
le.fit(y_train)               # fit on training labels (or whole y if preferred)
y_train_enc = le.transform(y_train)
y_test_enc  = le.transform(y_test)
# numeric index of target label in encoded space
target_index = int(np.where(le.classes_ == TARGET_LABEL)[0])

# --- Objective: maximize recall for TARGET_LABEL ---
def objective(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 50, 400),
        'max_depth': trial.suggest_int('max_depth', 3, 12),
        'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
        'subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 1.0),
        'gamma': trial.suggest_float('gamma', 0.0, 5.0),
        'reg_alpha': trial.suggest_float('reg_alpha', 0.0, 5.0),
        'reg_lambda': trial.suggest_float('reg_lambda', 0.0, 5.0),
        # stable args
        'random_state': 42,
        'use_label_encoder': False,
        'eval_metric': 'mlogloss'
    }

    # Build pipeline (SMOTE on training folds only)
    xgb = XGBClassifier(**params, n_jobs=1)   # n_jobs=1 to avoid nested parallelism in CV
    pipe = ImbPipeline([('smote', SMOTE(random_state=42)), ('xgb', xgb)])

    cv = StratifiedKFold(n_splits=CV_FOLDS, shuffle=True, random_state=42)
    recalls = []

    for train_idx, val_idx in cv.split(X_train, y_train_enc):
        X_t, X_v = X_train.iloc[train_idx], X_train.iloc[val_idx]
        y_t, y_v = y_train_enc[train_idx], y_train_enc[val_idx]

        pipe.fit(X_t, y_t)
        y_pred = pipe.predict(X_v)

        # compute recall per class in LABEL_ORDER and select target_index
        recs = recall_score(y_v, y_pred, labels=list(range(len(le.classes_))), average=None, zero_division=0)
        recall_high = recs[target_index]
        recalls.append(recall_high)

    return float(np.mean(recalls))

# --- Run Optuna study ---
sampler = TPESampler(seed=42)
study = optuna.create_study(direction='maximize', sampler=sampler, study_name='xgb_high_recall')
study.optimize(objective, n_trials=N_TRIALS, show_progress_bar=True)

print("\nBest CV mean High-recall:", study.best_value)
print("Best params:")
for k,v in study.best_params.items():
    print(f"  {k}: {v}")

# --- Train final pipeline with best params and evaluate on test set ---
best_params = study.best_params.copy()
# ensure required fixed args for final fit
best_params.update({'use_label_encoder': False, 'eval_metric': 'mlogloss', 'random_state': 42})
final_xgb = XGBClassifier(**best_params, n_jobs=-1)

final_pipe = ImbPipeline([('smote', SMOTE(random_state=42)), ('xgb', final_xgb)])
# fit with encoded y (pipeline will apply SMOTE inside)
final_pipe.fit(X_train, y_train_enc)

# predict (encoded), then decode for readable report
y_test_pred_enc = final_pipe.predict(X_test)
y_test_pred = le.inverse_transform(y_test_pred_enc)
y_test_orig = y_test  # original readable labels

print("\nFINAL Test Classification Report (labels in original names):")
print(classification_report(y_test_orig, y_test_pred, labels=le.classes_))
print("Confusion Matrix (rows=true, cols=predicted, order = le.classes_):")
print(confusion_matrix(y_test_orig, y_test_pred, labels=le.classes_))

/tmp/ipykernel_1540/2797660010.py:26: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  target_index = int(np.where(le.classes_ == TARGET_LABEL)[0])
[I 2026-07-09 09:54:38,502] A new study created in memory with name: xgb_high_recall

  0%|          | 0/40 [00:00<?, ?it/s]

/tmp/ipykernel_1540/2797660010.py:33: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:38] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:38] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:39] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 09:54:39,393] Trial 0 finished with value: 0.4532627865961199 and parameters: {'n_estimators': 181, 'max_depth': 12, 'learning_rate': 0.1205712628744377, 'subsample': 0.8394633936788146, 'colsample_bytree': 0.4936111842654619, 'gamma': 0.7799726016810132, 'reg_alpha': 0.2904180608409973, 'reg_lambda': 4.330880728874676}. Best is trial 0 with value: 0.4532627865961199.

/tmp/ipykernel_1540/2797660010.py:33: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:39] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:40] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:42] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 09:54:43,704] Trial 1 finished with value: 0.4656084656084656 and parameters: {'n_estimators': 260, 'max_depth': 10, 'learning_rate': 0.010725209743171997, 'subsample': 0.9879639408647978, 'colsample_bytree': 0.899465584480253, 'gamma': 1.0616955533913808, 'reg_alpha': 0.9091248360355031, 'reg_lambda': 0.9170225492671691}. Best is trial 1 with value: 0.4656084656084656.

/tmp/ipykernel_1540/2797660010.py:33: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:43] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:44] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:44] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 09:54:44,877] Trial 2 finished with value: 0.5145502645502645 and parameters: {'n_estimators': 156, 'max_depth': 8, 'learning_rate': 0.04345454109729477, 'subsample': 0.7164916560792167, 'colsample_bytree': 0.7671117368334277, 'gamma': 0.6974693032602092, 'reg_alpha': 1.4607232426760908, 'reg_lambda': 1.8318092164684585}. Best is trial 2 with value: 0.5145502645502645.

/tmp/ipykernel_1540/2797660010.py:33: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:44] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:45] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:46] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 09:54:46,889] Trial 3 finished with value: 0.5026455026455027 and parameters: {'n_estimators': 210, 'max_depth': 10, 'learning_rate': 0.019721610970574007, 'subsample': 0.8056937753654446, 'colsample_bytree': 0.7554487413172255, 'gamma': 0.23225206359998862, 'reg_alpha': 3.0377242595071916, 'reg_lambda': 0.8526206184364576}. Best is trial 2 with value: 0.5145502645502645.

/tmp/ipykernel_1540/2797660010.py:33: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:46] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:47] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:47] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/tmp/ipykernel_1540/2797660010.py:33: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:47] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 09:54:47,322] Trial 4 finished with value: 0.4898589065255732 and parameters: {'n_estimators': 72, 'max_depth': 12, 'learning_rate': 0.26690431824362526, 'subsample': 0.9233589392465844, 'colsample_bytree': 0.5827682615040224, 'gamma': 0.48836057003191935, 'reg_alpha': 3.4211651325607844, 'reg_lambda': 2.2007624686980067}. Best is trial 2 with value: 0.5145502645502645.

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:47] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:47] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 09:54:47,947] Trial 5 finished with value: 0.5392416225749559 and parameters: {'n_estimators': 92, 'max_depth': 7, 'learning_rate': 0.011240768803005551, 'subsample': 0.9637281608315128, 'colsample_bytree': 0.5552679889600102, 'gamma': 3.31261142176991, 'reg_alpha': 1.5585553804470549, 'reg_lambda': 2.600340105889054}. Best is trial 5 with value: 0.5392416225749559.

/tmp/ipykernel_1540/2797660010.py:33: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:47] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:48] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:48] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/tmp/ipykernel_1540/2797660010.py:33: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-07-09 09:54:48,650] Trial 6 finished with value: 0.6353615520282186 and parameters: {'n_estimators': 241, 'max_depth': 4, 'learning_rate': 0.27051668818999286, 'subsample': 0.9100531293444458, 'colsample_bytree': 0.9636993649385135, 'gamma': 4.474136752138244, 'reg_alpha': 2.9894998940554256, 'reg_lambda': 4.609371175115584}. Best is trial 6 with value: 0.6353615520282186.

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:48] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:48] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:48] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/tmp/ipykernel_1540/2797660010.py:33: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:49] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 09:54:49,124] Trial 7 finished with value: 0.6362433862433862 and parameters: {'n_estimators': 81, 'max_depth': 4, 'learning_rate': 0.011662890273931383, 'subsample': 0.7301321323053057, 'colsample_bytree': 0.6332063738136893, 'gamma': 1.3567451588694794, 'reg_alpha': 4.143687545759647, 'reg_lambda': 1.7837666334679465}. Best is trial 7 with value: 0.6362433862433862.

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:49] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:49] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/tmp/ipykernel_1540/2797660010.py:33: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-07-09 09:54:49,843] Trial 8 finished with value: 0.5749559082892416 and parameters: {'n_estimators': 148, 'max_depth': 8, 'learning_rate': 0.016149614799999188, 'subsample': 0.9208787923016158, 'colsample_bytree': 0.44473038620786254, 'gamma': 4.9344346830025865, 'reg_alpha': 3.861223846483287, 'reg_lambda': 0.993578407670862}. Best is trial 7 with value: 0.6362433862433862.

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:49] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:50] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:50] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/tmp/ipykernel_1540/2797660010.py:33: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-07-09 09:54:50,457] Trial 9 finished with value: 0.4775132275132275 and parameters: {'n_estimators': 51, 'max_depth': 11, 'learning_rate': 0.11069143219393454, 'subsample': 0.8916028672163949, 'colsample_bytree': 0.8627622080115674, 'gamma': 0.3702232586704518, 'reg_alpha': 1.7923286427213632, 'reg_lambda': 0.5793452976256486}. Best is trial 7 with value: 0.6362433862433862.

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:50] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:50] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:51] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 09:54:51,875] Trial 10 finished with value: 0.6234567901234568 and parameters: {'n_estimators': 381, 'max_depth': 3, 'learning_rate': 0.03504750508385013, 'subsample': 0.6071847502459279, 'colsample_bytree': 0.6770453467430337, 'gamma': 2.1047238510211645, 'reg_alpha': 4.7988537297270994, 'reg_lambda': 3.4498740332905546}. Best is trial 7 with value: 0.6362433862433862.

/tmp/ipykernel_1540/2797660010.py:33: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:51] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:52] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:52] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 09:54:52,777] Trial 11 finished with value: 0.6358024691358025 and parameters: {'n_estimators': 310, 'max_depth': 3, 'learning_rate': 0.2818562489418465, 'subsample': 0.7201993018480907, 'colsample_bytree': 0.947587754625664, 'gamma': 4.947553985693858, 'reg_alpha': 2.653975221141253, 'reg_lambda': 4.6778093804071235}. Best is trial 7 with value: 0.6362433862433862.

/tmp/ipykernel_1540/2797660010.py:33: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:52] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:53] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:53] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 09:54:54,016] Trial 12 finished with value: 0.6234567901234568 and parameters: {'n_estimators': 325, 'max_depth': 5, 'learning_rate': 0.09005954111408214, 'subsample': 0.7234707775332928, 'colsample_bytree': 0.6642964173146435, 'gamma': 2.8452976255168942, 'reg_alpha': 4.9020471453382655, 'reg_lambda': 3.5161700195678636}. Best is trial 7 with value: 0.6362433862433862.

/tmp/ipykernel_1540/2797660010.py:33: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:54] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:54] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:55] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 09:54:56,075] Trial 13 finished with value: 0.6111111111111112 and parameters: {'n_estimators': 304, 'max_depth': 5, 'learning_rate': 0.05417955236254975, 'subsample': 0.6908556046603513, 'colsample_bytree': 0.9880253243162445, 'gamma': 3.599197097805107, 'reg_alpha': 2.2982654518121506, 'reg_lambda': 0.09688175778262487}. Best is trial 7 with value: 0.6362433862433862.

/tmp/ipykernel_1540/2797660010.py:33: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:56] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:56] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:57] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 09:54:57,481] Trial 14 finished with value: 0.6115520282186949 and parameters: {'n_estimators': 357, 'max_depth': 3, 'learning_rate': 0.17646596150449267, 'subsample': 0.7697922802824734, 'colsample_bytree': 0.8342650606282753, 'gamma': 1.7238914372636158, 'reg_alpha': 4.135582728785615, 'reg_lambda': 4.980084946806068}. Best is trial 7 with value: 0.6362433862433862.

/tmp/ipykernel_1540/2797660010.py:33: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:57] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:57] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:57] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 09:54:58,057] Trial 15 finished with value: 0.6115520282186949 and parameters: {'n_estimators': 117, 'max_depth': 5, 'learning_rate': 0.06689802001564377, 'subsample': 0.6539913908027278, 'colsample_bytree': 0.671395787726565, 'gamma': 4.071046469152574, 'reg_alpha': 2.68866352541103, 'reg_lambda': 3.4370780373026855}. Best is trial 7 with value: 0.6362433862433862.

/tmp/ipykernel_1540/2797660010.py:33: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:58] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:58] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:58] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 09:54:59,313] Trial 16 finished with value: 0.5868606701940036 and parameters: {'n_estimators': 282, 'max_depth': 6, 'learning_rate': 0.027256417097362772, 'subsample': 0.7545478777043765, 'colsample_bytree': 0.4059294238322583, 'gamma': 2.2695499753360395, 'reg_alpha': 4.119939070302924, 'reg_lambda': 1.689298476517112}. Best is trial 7 with value: 0.6362433862433862.

/tmp/ipykernel_1540/2797660010.py:33: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:59] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:59] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:54:59] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 09:55:00,123] Trial 17 finished with value: 0.5630511463844797 and parameters: {'n_estimators': 220, 'max_depth': 3, 'learning_rate': 0.17441159401168876, 'subsample': 0.6616159871845755, 'colsample_bytree': 0.7906646835873276, 'gamma': 1.4070712978947963, 'reg_alpha': 2.2899828989740874, 'reg_lambda': 2.7214466009323655}. Best is trial 7 with value: 0.6362433862433862.

/tmp/ipykernel_1540/2797660010.py:33: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:00] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:00] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:01] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 09:55:01,567] Trial 18 finished with value: 0.6115520282186949 and parameters: {'n_estimators': 348, 'max_depth': 4, 'learning_rate': 0.020452842581902022, 'subsample': 0.8157091115658528, 'colsample_bytree': 0.5964943525856926, 'gamma': 2.707668129200069, 'reg_alpha': 3.497895792219339, 'reg_lambda': 3.9823934447105245}. Best is trial 7 with value: 0.6362433862433862.

/tmp/ipykernel_1540/2797660010.py:33: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:01] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:02] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:02] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 09:55:02,887] Trial 19 finished with value: 0.6234567901234568 and parameters: {'n_estimators': 400, 'max_depth': 4, 'learning_rate': 0.07097783577505477, 'subsample': 0.6003429536877471, 'colsample_bytree': 0.9360930453448412, 'gamma': 3.835552637799392, 'reg_alpha': 4.480242120429778, 'reg_lambda': 3.055427341145145}. Best is trial 7 with value: 0.6362433862433862.

/tmp/ipykernel_1540/2797660010.py:33: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:02] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:03] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:03] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 09:55:03,531] Trial 20 finished with value: 0.6111111111111112 and parameters: {'n_estimators': 113, 'max_depth': 6, 'learning_rate': 0.03197931715480902, 'subsample': 0.7603864950608997, 'colsample_bytree': 0.7298136752292095, 'gamma': 4.868293089081371, 'reg_alpha': 2.231610042250181, 'reg_lambda': 1.4410218447342344}. Best is trial 7 with value: 0.6362433862433862.

/tmp/ipykernel_1540/2797660010.py:33: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:03] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:03] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:04] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 09:55:04,244] Trial 21 finished with value: 0.6234567901234568 and parameters: {'n_estimators': 236, 'max_depth': 4, 'learning_rate': 0.25721460452771194, 'subsample': 0.8534845791526902, 'colsample_bytree': 0.9977352306431471, 'gamma': 4.649071227271153, 'reg_alpha': 3.0247906044271664, 'reg_lambda': 4.731535755175757}. Best is trial 7 with value: 0.6362433862433862.

/tmp/ipykernel_1540/2797660010.py:33: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:04] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:04] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:04] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 09:55:05,085] Trial 22 finished with value: 0.6358024691358025 and parameters: {'n_estimators': 263, 'max_depth': 4, 'learning_rate': 0.16936786695781086, 'subsample': 0.6650859932869133, 'colsample_bytree': 0.9331424114597132, 'gamma': 4.3216765659278265, 'reg_alpha': 3.4714940062459383, 'reg_lambda': 4.278695228324326}. Best is trial 7 with value: 0.6362433862433862.

/tmp/ipykernel_1540/2797660010.py:33: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:05] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:05] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:05] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 09:55:05,970] Trial 23 finished with value: 0.6115520282186949 and parameters: {'n_estimators': 291, 'max_depth': 3, 'learning_rate': 0.1973066832994606, 'subsample': 0.6549612269166183, 'colsample_bytree': 0.9171398670651845, 'gamma': 4.259396053173479, 'reg_alpha': 3.7962201960759914, 'reg_lambda': 4.0663912693838}. Best is trial 7 with value: 0.6362433862433862.

/tmp/ipykernel_1540/2797660010.py:33: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:06] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:06] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:06] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 09:55:07,116] Trial 24 finished with value: 0.6234567901234568 and parameters: {'n_estimators': 331, 'max_depth': 6, 'learning_rate': 0.1362669379696494, 'subsample': 0.6910578410089723, 'colsample_bytree': 0.8589154424710677, 'gamma': 2.970624039974232, 'reg_alpha': 3.421227468574111, 'reg_lambda': 3.8702374758549567}. Best is trial 7 with value: 0.6362433862433862.

/tmp/ipykernel_1540/2797660010.py:33: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:07] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:07] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:07] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 09:55:08,202] Trial 25 finished with value: 0.6238977072310404 and parameters: {'n_estimators': 190, 'max_depth': 5, 'learning_rate': 0.29608828212709076, 'subsample': 0.734793733388615, 'colsample_bytree': 0.8213586357899512, 'gamma': 3.441705817567301, 'reg_alpha': 4.365358328757959, 'reg_lambda': 4.422481483582056}. Best is trial 7 with value: 0.6362433862433862.

/tmp/ipykernel_1540/2797660010.py:33: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:08] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:08] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:09] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 09:55:09,681] Trial 26 finished with value: 0.6358024691358025 and parameters: {'n_estimators': 267, 'max_depth': 4, 'learning_rate': 0.20388839799104394, 'subsample': 0.691576043305808, 'colsample_bytree': 0.8895219346541637, 'gamma': 4.179680494862909, 'reg_alpha': 2.6894420277659448, 'reg_lambda': 4.986330282821735}. Best is trial 7 with value: 0.6362433862433862.

/tmp/ipykernel_1540/2797660010.py:33: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:09] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:10] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:10] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 09:55:10,946] Trial 27 finished with value: 0.6115520282186949 and parameters: {'n_estimators': 311, 'max_depth': 3, 'learning_rate': 0.14930898212167865, 'subsample': 0.640133712069693, 'colsample_bytree': 0.5000127792621848, 'gamma': 2.390310897251647, 'reg_alpha': 3.6948534515506575, 'reg_lambda': 2.4187270614318424}. Best is trial 7 with value: 0.6362433862433862.

/tmp/ipykernel_1540/2797660010.py:33: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:10] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:11] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:11] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 09:55:11,706] Trial 28 finished with value: 0.5996472663139331 and parameters: {'n_estimators': 152, 'max_depth': 7, 'learning_rate': 0.09365098199228729, 'subsample': 0.7911041380828158, 'colsample_bytree': 0.947304878818817, 'gamma': 1.7567428650018955, 'reg_alpha': 4.501002847844079, 'reg_lambda': 3.0217260432322264}. Best is trial 7 with value: 0.6362433862433862.

/tmp/ipykernel_1540/2797660010.py:33: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:11] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:12] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:12] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 09:55:12,698] Trial 29 finished with value: 0.501763668430335 and parameters: {'n_estimators': 179, 'max_depth': 4, 'learning_rate': 0.21931013667984453, 'subsample': 0.7087705365387703, 'colsample_bytree': 0.7145546303227438, 'gamma': 0.014255272511687345, 'reg_alpha': 0.8241310168655023, 'reg_lambda': 4.168521437735028}. Best is trial 7 with value: 0.6362433862433862.

/tmp/ipykernel_1540/2797660010.py:33: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:12] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:13] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:13] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 09:55:14,292] Trial 30 finished with value: 0.5873015873015873 and parameters: {'n_estimators': 364, 'max_depth': 5, 'learning_rate': 0.013427312592104598, 'subsample': 0.848981751956403, 'colsample_bytree': 0.6206301118344929, 'gamma': 4.528011338166419, 'reg_alpha': 0.2137259003982077, 'reg_lambda': 4.413342492896184}. Best is trial 7 with value: 0.6362433862433862.

/tmp/ipykernel_1540/2797660010.py:33: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:14] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:14] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:14] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 09:55:15,138] Trial 31 finished with value: 0.6353615520282186 and parameters: {'n_estimators': 265, 'max_depth': 4, 'learning_rate': 0.2142792385360814, 'subsample': 0.685151980362682, 'colsample_bytree': 0.8752935066740243, 'gamma': 4.046336950382393, 'reg_alpha': 2.659748417708634, 'reg_lambda': 4.947541140381995}. Best is trial 7 with value: 0.6362433862433862.

/tmp/ipykernel_1540/2797660010.py:33: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:15] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:15] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:15] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 09:55:16,005] Trial 32 finished with value: 0.6477072310405644 and parameters: {'n_estimators': 267, 'max_depth': 3, 'learning_rate': 0.1509392646072631, 'subsample': 0.6299467123415943, 'colsample_bytree': 0.9124612162369469, 'gamma': 4.980315590714612, 'reg_alpha': 2.6580436995803653, 'reg_lambda': 3.7380325107140413}. Best is trial 32 with value: 0.6477072310405644.

/tmp/ipykernel_1540/2797660010.py:33: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:16] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:16] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:16] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 09:55:16,840] Trial 33 finished with value: 0.6604938271604938 and parameters: {'n_estimators': 247, 'max_depth': 3, 'learning_rate': 0.11925775090495656, 'subsample': 0.6233655810318868, 'colsample_bytree': 0.9121866442168038, 'gamma': 4.985091673277764, 'reg_alpha': 3.235291325242966, 'reg_lambda': 3.824330236853218}. Best is trial 33 with value: 0.6604938271604938.

/tmp/ipykernel_1540/2797660010.py:33: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:16] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:17] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:17] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 09:55:17,656] Trial 34 finished with value: 0.6234567901234568 and parameters: {'n_estimators': 241, 'max_depth': 3, 'learning_rate': 0.10264247596286978, 'subsample': 0.6255292026073196, 'colsample_bytree': 0.8037723962343313, 'gamma': 4.893084844877567, 'reg_alpha': 1.9167408156228212, 'reg_lambda': 3.754221405517247}. Best is trial 33 with value: 0.6604938271604938.

/tmp/ipykernel_1540/2797660010.py:33: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:17] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:17] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:18] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 09:55:18,378] Trial 35 finished with value: 0.6477072310405644 and parameters: {'n_estimators': 200, 'max_depth': 3, 'learning_rate': 0.12682153313051595, 'subsample': 0.6273885770625389, 'colsample_bytree': 0.9014393888598942, 'gamma': 4.643500501470426, 'reg_alpha': 3.0977952570595706, 'reg_lambda': 3.0118909969905245}. Best is trial 33 with value: 0.6604938271604938.

/tmp/ipykernel_1540/2797660010.py:33: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:18] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:18] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:18] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 09:55:19,182] Trial 36 finished with value: 0.6234567901234568 and parameters: {'n_estimators': 206, 'max_depth': 3, 'learning_rate': 0.07820748703169571, 'subsample': 0.6259979310022742, 'colsample_bytree': 0.8969975138939853, 'gamma': 3.7708511368779134, 'reg_alpha': 3.1502193150846702, 'reg_lambda': 2.9469535724112843}. Best is trial 33 with value: 0.6604938271604938.

/tmp/ipykernel_1540/2797660010.py:33: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:19] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:19] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:19] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 09:55:19,879] Trial 37 finished with value: 0.6238977072310404 and parameters: {'n_estimators': 171, 'max_depth': 3, 'learning_rate': 0.053257580989956685, 'subsample': 0.6320568813951757, 'colsample_bytree': 0.5294194831129171, 'gamma': 4.661230074006847, 'reg_alpha': 3.238979418540123, 'reg_lambda': 2.2119607961551417}. Best is trial 33 with value: 0.6604938271604938.

/tmp/ipykernel_1540/2797660010.py:33: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:19] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:20] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:20] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 09:55:20,437] Trial 38 finished with value: 0.6362433862433862 and parameters: {'n_estimators': 129, 'max_depth': 5, 'learning_rate': 0.12840788656324284, 'subsample': 0.61115107840185, 'colsample_bytree': 0.7648461225574379, 'gamma': 4.595340531170811, 'reg_alpha': 4.004861062472679, 'reg_lambda': 3.301865993077804}. Best is trial 33 with value: 0.6604938271604938.

/tmp/ipykernel_1540/2797660010.py:33: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:20] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:20] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:21] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 09:55:21,481] Trial 39 finished with value: 0.6358024691358025 and parameters: {'n_estimators': 89, 'max_depth': 4, 'learning_rate': 0.024436945339636054, 'subsample': 0.6677142024033199, 'colsample_bytree': 0.8504078593694411, 'gamma': 1.1978762065399482, 'reg_alpha': 2.9797085577743547, 'reg_lambda': 3.6623788227337997}. Best is trial 33 with value: 0.6604938271604938.

Best CV mean High-recall: 0.6604938271604938
Best params:
  n_estimators: 247
  max_depth: 3
  learning_rate: 0.11925775090495656
  subsample: 0.6233655810318868
  colsample_bytree: 0.9121866442168038
  gamma: 4.985091673277764
  reg_alpha: 3.235291325242966
  reg_lambda: 3.824330236853218

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:55:21] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

FINAL Test Classification Report (labels in original names):
              precision    recall  f1-score   support

        High       0.21      0.55      0.31        20
         Low       0.70      0.74      0.72        65
      Medium       0.91      0.80      0.85       315

    accuracy                           0.78       400
   macro avg       0.60      0.70      0.62       400
weighted avg       0.84      0.78      0.80       400

Confusion Matrix (rows=true, cols=predicted, order = le.classes_):
[[ 11   0   9]
 [  0  48  17]
 [ 41  21 253]]

In [56]:
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder
import numpy as np

# 1. Encode target labels (if not already numeric)
le = LabelEncoder()
y_train_enc = le.fit_transform(y_train)
y_test_enc = le.transform(y_test)

# 2. Compute class weights inversely proportional to class frequencies
classes, counts = np.unique(y_train_enc, return_counts=True)
class_weights = {cls: max(counts)/count for cls, count in zip(classes, counts)}
print("Class Weights:", class_weights)

# 3. Initialize XGBoost with weights
xgb_weighted = XGBClassifier(
    objective='multi:softmax',
    num_class=len(classes),
    eval_metric='mlogloss',
    random_state=42,
    n_estimators=105,
    max_depth=3,
    learning_rate=0.014843806162322944,
    subsample=0.7730982444721965,
    colsample_bytree=0.8509237341976973,
    gamma=4.134336554829186,
    reg_alpha=4.453508368364819,
    reg_lambda=2.616923339470738,
    n_jobs=-1
)

# 4. Fit model with per-sample weights
sample_weights = np.array([class_weights[y] for y in y_train_enc])
xgb_weighted.fit(X_train, y_train_enc, sample_weight=sample_weights)

# 5. Evaluate
y_pred_enc = xgb_weighted.predict(X_test)
print("Class-weighted XGBoost - Classification Report")
print(classification_report(y_test_enc, y_pred_enc, target_names=le.classes_))
print("Confusion Matrix")
print(confusion_matrix(y_test_enc, y_pred_enc))

Class Weights: {np.int64(0): np.float64(15.353658536585366), np.int64(1): np.float64(4.861003861003861), np.int64(2): np.float64(1.0)}
Class-weighted XGBoost - Classification Report
              precision    recall  f1-score   support

        High       0.21      0.75      0.33        20
         Low       0.43      0.80      0.56        65
      Medium       0.91      0.60      0.72       315

    accuracy                           0.64       400
   macro avg       0.52      0.72      0.54       400
weighted avg       0.80      0.64      0.68       400

Confusion Matrix
[[ 15   0   5]
 [  0  52  13]
 [ 56  70 189]]

In [57]:
# Optuna tuning for class-weighted XGBoost (optimize macro-F1)
import optuna
from optuna.samplers import TPESampler
from xgboost import XGBClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import f1_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder
import numpy as np

# ----------------------
# Prepare encoded labels
# ----------------------
le = LabelEncoder()
le.fit(y_train)               # fit encoder on training labels
y_train_enc = le.transform(y_train)
y_test_enc  = le.transform(y_test)
n_classes = len(le.classes_)

# ----------------------
# Objective: maximize macro-F1
# ----------------------
def objective(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 50, 400),
        'max_depth': trial.suggest_int('max_depth', 2, 12),
        'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
        'subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 1.0),
        'gamma': trial.suggest_float('gamma', 0.0, 5.0),
        'reg_alpha': trial.suggest_float('reg_alpha', 0.0, 5.0),
        'reg_lambda': trial.suggest_float('reg_lambda', 0.0, 5.0),
        # stable args:
        'use_label_encoder': False,
        'eval_metric': 'mlogloss',
        # set n_jobs=1 inside CV to avoid nested parallelism
    }

    cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)
    scores = []

    for train_idx, val_idx in cv.split(X_train, y_train_enc):
        X_t, X_v = X_train.iloc[train_idx], X_train.iloc[val_idx]
        y_t, y_v = y_train_enc[train_idx], y_train_enc[val_idx]

        # compute class weights from the fold's training data
        classes, counts = np.unique(y_t, return_counts=True)
        # simple inverse frequency scaling
        class_weight_map = {cls: float(max(counts) / cnt) for cls, cnt in zip(classes, counts)}
        sample_weights = np.array([class_weight_map[y] for y in y_t])

        # instantiate classifier with n_jobs=1 for CV
        model = XGBClassifier(**params, n_jobs=1, random_state=42)

        # fit with per-sample weights
        model.fit(X_t, y_t, sample_weight=sample_weights, verbose=False)

        y_pred = model.predict(X_v)
        scores.append(f1_score(y_v, y_pred, average='macro'))

    # return mean macro-F1 across folds
    return float(np.mean(scores))

# ----------------------
# Run Optuna study
# ----------------------
sampler = TPESampler(seed=42)
study = optuna.create_study(direction='maximize', sampler=sampler, study_name='xgb_class_weighted_macroF1')

# fewer trials to start; increase to 50-150 when comfortable
study.optimize(objective, n_trials=40, show_progress_bar=True)

print("Best CV macro-F1:", study.best_value)
print("Best params:")
for k, v in study.best_params.items():
    print(f"  {k}: {v}")

# ----------------------
# Train final model on full training set using class weights
# ----------------------
best = study.best_params.copy()
best.update({'use_label_encoder': False, 'eval_metric': 'mlogloss', 'random_state': 42})

# compute final sample weights from full training set
classes, counts = np.unique(y_train_enc, return_counts=True)
final_class_weight_map = {cls: float(max(counts)/cnt) for cls, cnt in zip(classes, counts)}
final_sample_weights = np.array([final_class_weight_map[y] for y in y_train_enc])

final_xgb = XGBClassifier(**best, n_jobs=-1)
final_xgb.fit(X_train, y_train_enc, sample_weight=final_sample_weights, verbose=False)

# Evaluate on untouched test set
y_test_pred_enc = final_xgb.predict(X_test)
y_test_pred = le.inverse_transform(y_test_pred_enc)
y_test_orig = y_test  # already readable labels

print("\nFINAL Test Classification Report (class-weighted XGB):")
print(classification_report(y_test_orig, y_test_pred, labels=le.classes_))
print("Confusion Matrix (rows=true, cols=pred):")
print(confusion_matrix(y_test_orig, y_test_pred, labels=le.classes_))

[I 2026-07-09 10:01:05,553] A new study created in memory with name: xgb_class_weighted_macroF1

  0%|          | 0/40 [00:00<?, ?it/s]

/tmp/ipykernel_1540/3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:05] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:06] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:07] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 10:01:07,444] Trial 0 finished with value: 0.7031973820514495 and parameters: {'n_estimators': 181, 'max_depth': 12, 'learning_rate': 0.06504856968981275, 'subsample': 0.8394633936788146, 'colsample_bytree': 0.4936111842654619, 'gamma': 0.7799726016810132, 'reg_alpha': 0.2904180608409973, 'reg_lambda': 4.330880728874676}. Best is trial 0 with value: 0.7031973820514495.

/tmp/ipykernel_1540/3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:07] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:09] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:10] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 10:01:12,059] Trial 1 finished with value: 0.6495679698073193 and parameters: {'n_estimators': 260, 'max_depth': 9, 'learning_rate': 0.001124579825911934, 'subsample': 0.9879639408647978, 'colsample_bytree': 0.899465584480253, 'gamma': 1.0616955533913808, 'reg_alpha': 0.9091248360355031, 'reg_lambda': 0.9170225492671691}. Best is trial 0 with value: 0.7031973820514495.

/tmp/ipykernel_1540/3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:12] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:12] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:13] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 10:01:13,768] Trial 2 finished with value: 0.6792888831998224 and parameters: {'n_estimators': 156, 'max_depth': 7, 'learning_rate': 0.01174843954800703, 'subsample': 0.7164916560792167, 'colsample_bytree': 0.7671117368334277, 'gamma': 0.6974693032602092, 'reg_alpha': 1.4607232426760908, 'reg_lambda': 1.8318092164684585}. Best is trial 0 with value: 0.7031973820514495.

/tmp/ipykernel_1540/3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:13] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:14] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:15] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 10:01:16,360] Trial 3 finished with value: 0.6754483109492289 and parameters: {'n_estimators': 210, 'max_depth': 10, 'learning_rate': 0.003123317753376431, 'subsample': 0.8056937753654446, 'colsample_bytree': 0.7554487413172255, 'gamma': 0.23225206359998862, 'reg_alpha': 3.0377242595071916, 'reg_lambda': 0.8526206184364576}. Best is trial 0 with value: 0.7031973820514495.

/tmp/ipykernel_1540/3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:16] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:16] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:16] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/tmp/ipykernel_1540/3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:16] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 10:01:16,677] Trial 4 finished with value: 0.7188163893456238 and parameters: {'n_estimators': 72, 'max_depth': 12, 'learning_rate': 0.24659691172104828, 'subsample': 0.9233589392465844, 'colsample_bytree': 0.5827682615040224, 'gamma': 0.48836057003191935, 'reg_alpha': 3.4211651325607844, 'reg_lambda': 2.2007624686980067}. Best is trial 4 with value: 0.7188163893456238.

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:16] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:17] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 10:01:17,264] Trial 5 finished with value: 0.6372918798639652 and parameters: {'n_estimators': 92, 'max_depth': 7, 'learning_rate': 0.0012167028814593455, 'subsample': 0.9637281608315128, 'colsample_bytree': 0.5552679889600102, 'gamma': 3.31261142176991, 'reg_alpha': 1.5585553804470549, 'reg_lambda': 2.600340105889054}. Best is trial 4 with value: 0.7188163893456238.

/tmp/ipykernel_1540/3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:17] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:17] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:17] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/tmp/ipykernel_1540/3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:17] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 10:01:17,704] Trial 6 finished with value: 0.6655728624811524 and parameters: {'n_estimators': 241, 'max_depth': 4, 'learning_rate': 0.25221951700214285, 'subsample': 0.9100531293444458, 'colsample_bytree': 0.9636993649385135, 'gamma': 4.474136752138244, 'reg_alpha': 2.9894998940554256, 'reg_lambda': 4.609371175115584}. Best is trial 4 with value: 0.7188163893456238.

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:17] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:17] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/tmp/ipykernel_1540/3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:18] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 10:01:18,052] Trial 7 finished with value: 0.5951849134009485 and parameters: {'n_estimators': 81, 'max_depth': 4, 'learning_rate': 0.001294295611551122, 'subsample': 0.7301321323053057, 'colsample_bytree': 0.6332063738136893, 'gamma': 1.3567451588694794, 'reg_alpha': 4.143687545759647, 'reg_lambda': 1.7837666334679465}. Best is trial 4 with value: 0.7188163893456238.

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:18] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:18] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 10:01:18,692] Trial 8 finished with value: 0.606126935045054 and parameters: {'n_estimators': 148, 'max_depth': 7, 'learning_rate': 0.0022340165853190056, 'subsample': 0.9208787923016158, 'colsample_bytree': 0.44473038620786254, 'gamma': 4.9344346830025865, 'reg_alpha': 3.861223846483287, 'reg_lambda': 0.993578407670862}. Best is trial 4 with value: 0.7188163893456238.

/tmp/ipykernel_1540/3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:18] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:18] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:19] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/tmp/ipykernel_1540/3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-07-09 10:01:19,244] Trial 9 finished with value: 0.6899055537537904 and parameters: {'n_estimators': 51, 'max_depth': 10, 'learning_rate': 0.0563600475052774, 'subsample': 0.8916028672163949, 'colsample_bytree': 0.8627622080115674, 'gamma': 0.3702232586704518, 'reg_alpha': 1.7923286427213632, 'reg_lambda': 0.5793452976256486}. Best is trial 4 with value: 0.7188163893456238.

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:19] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:19] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:19] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 10:01:20,080] Trial 10 finished with value: 0.5660860740518694 and parameters: {'n_estimators': 381, 'max_depth': 2, 'learning_rate': 0.009739280447133345, 'subsample': 0.6071847502459279, 'colsample_bytree': 0.6383254458186773, 'gamma': 2.2692936416707705, 'reg_alpha': 4.7988537297270994, 'reg_lambda': 3.4498740332905546}. Best is trial 4 with value: 0.7188163893456238.

/tmp/ipykernel_1540/3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:20] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:20] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:20] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 10:01:20,694] Trial 11 finished with value: 0.700675512930779 and parameters: {'n_estimators': 325, 'max_depth': 12, 'learning_rate': 0.2924663013251175, 'subsample': 0.8369993090060779, 'colsample_bytree': 0.4128373290348984, 'gamma': 1.8524392898501765, 'reg_alpha': 0.339101338813105, 'reg_lambda': 4.6778093804071235}. Best is trial 4 with value: 0.7188163893456238.

/tmp/ipykernel_1540/3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:20] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:20] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:21] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 10:01:21,514] Trial 12 finished with value: 0.708367177595068 and parameters: {'n_estimators': 144, 'max_depth': 12, 'learning_rate': 0.10066481531401737, 'subsample': 0.8208104960302076, 'colsample_bytree': 0.5260149855525312, 'gamma': 0.04655577784569376, 'reg_alpha': 2.591574764832035, 'reg_lambda': 3.577221997078211}. Best is trial 4 with value: 0.7188163893456238.

/tmp/ipykernel_1540/3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:21] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:21] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:22] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 10:01:22,392] Trial 13 finished with value: 0.7019224350448585 and parameters: {'n_estimators': 137, 'max_depth': 12, 'learning_rate': 0.09193282756125644, 'subsample': 0.7544943171389786, 'colsample_bytree': 0.5878370416765092, 'gamma': 0.010871103773072155, 'reg_alpha': 2.821850063415317, 'reg_lambda': 3.2819754180926792}. Best is trial 4 with value: 0.7188163893456238.

/tmp/ipykernel_1540/3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:22] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:22] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:22] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/tmp/ipykernel_1540/3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:22] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 10:01:22,794] Trial 14 finished with value: 0.6905988173140161 and parameters: {'n_estimators': 107, 'max_depth': 10, 'learning_rate': 0.12320860729899048, 'subsample': 0.7886502691917054, 'colsample_bytree': 0.7127307841623679, 'gamma': 1.7997978549822589, 'reg_alpha': 2.341639101406412, 'reg_lambda': 3.4833611098443398}. Best is trial 4 with value: 0.7188163893456238.

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:22] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:23] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/tmp/ipykernel_1540/3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:23] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 10:01:23,165] Trial 15 finished with value: 0.650890032809195 and parameters: {'n_estimators': 65, 'max_depth': 11, 'learning_rate': 0.024222103033977958, 'subsample': 0.6662225125541512, 'colsample_bytree': 0.5178731437442949, 'gamma': 2.50252327462636, 'reg_alpha': 3.7414397178578134, 'reg_lambda': 2.5122573045605012}. Best is trial 4 with value: 0.7188163893456238.

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:23] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:23] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/tmp/ipykernel_1540/3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:23] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 10:01:23,561] Trial 16 finished with value: 0.7109156044050765 and parameters: {'n_estimators': 106, 'max_depth': 9, 'learning_rate': 0.17355499306143987, 'subsample': 0.8667527577505644, 'colsample_bytree': 0.6592110238826213, 'gamma': 1.3934822495513066, 'reg_alpha': 2.2387103134222355, 'reg_lambda': 3.9513134920360846}. Best is trial 4 with value: 0.7188163893456238.

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:23] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:23] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/tmp/ipykernel_1540/3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:23] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 10:01:23,882] Trial 17 finished with value: 0.6885675144637015 and parameters: {'n_estimators': 110, 'max_depth': 8, 'learning_rate': 0.1708497322072893, 'subsample': 0.8743018874271551, 'colsample_bytree': 0.6805423650424057, 'gamma': 3.229693216850281, 'reg_alpha': 3.4010175758223853, 'reg_lambda': 0.11782849329702616}. Best is trial 4 with value: 0.7188163893456238.

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:24] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:24] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 10:01:24,745] Trial 18 finished with value: 0.6785845151742468 and parameters: {'n_estimators': 203, 'max_depth': 5, 'learning_rate': 0.028883304690171332, 'subsample': 0.9331045866127845, 'colsample_bytree': 0.8298614728257692, 'gamma': 1.3941421020797948, 'reg_alpha': 4.510334932359586, 'reg_lambda': 4.0245283843714255}. Best is trial 4 with value: 0.7188163893456238.

/tmp/ipykernel_1540/3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:24] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:24] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:24] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/tmp/ipykernel_1540/3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:25] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 10:01:25,067] Trial 19 finished with value: 0.6889870103072453 and parameters: {'n_estimators': 111, 'max_depth': 9, 'learning_rate': 0.17917337816646134, 'subsample': 0.9531175927762593, 'colsample_bytree': 0.6116415783922288, 'gamma': 2.9575883549786286, 'reg_alpha': 2.1257108134124696, 'reg_lambda': 2.648527420298997}. Best is trial 4 with value: 0.7188163893456238.

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:25] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:25] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/tmp/ipykernel_1540/3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:25] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 10:01:25,506] Trial 20 finished with value: 0.67871759791703 and parameters: {'n_estimators': 58, 'max_depth': 9, 'learning_rate': 0.047642185863514916, 'subsample': 0.869338681861774, 'colsample_bytree': 0.7292625940351332, 'gamma': 1.599639411587253, 'reg_alpha': 3.448301446014497, 'reg_lambda': 1.5943105408092473}. Best is trial 4 with value: 0.7188163893456238.

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:25] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:26] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 10:01:26,387] Trial 21 finished with value: 0.7171465984870125 and parameters: {'n_estimators': 134, 'max_depth': 11, 'learning_rate': 0.10828652304402672, 'subsample': 0.8340306259994301, 'colsample_bytree': 0.5231330014724231, 'gamma': 0.6473606693837791, 'reg_alpha': 2.4846695287896945, 'reg_lambda': 4.077685359666595}. Best is trial 4 with value: 0.7188163893456238.

/tmp/ipykernel_1540/3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:26] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:26] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:26] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 10:01:27,201] Trial 22 finished with value: 0.7015553205063959 and parameters: {'n_estimators': 128, 'max_depth': 11, 'learning_rate': 0.17754671088040883, 'subsample': 0.8688201372003878, 'colsample_bytree': 0.4558310257067228, 'gamma': 0.7161461675404843, 'reg_alpha': 2.086661384408223, 'reg_lambda': 4.0058694070379754}. Best is trial 4 with value: 0.7188163893456238.

/tmp/ipykernel_1540/3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:27] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:27] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:27] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 10:01:28,216] Trial 23 finished with value: 0.7213864704242209 and parameters: {'n_estimators': 182, 'max_depth': 11, 'learning_rate': 0.1234727012102534, 'subsample': 0.7768697837788987, 'colsample_bytree': 0.5706661598751535, 'gamma': 1.022174195802494, 'reg_alpha': 3.237402200388701, 'reg_lambda': 4.947306277660575}. Best is trial 23 with value: 0.7213864704242209.

/tmp/ipykernel_1540/3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:28] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:28] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:29] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 10:01:29,383] Trial 24 finished with value: 0.6951320815292173 and parameters: {'n_estimators': 176, 'max_depth': 11, 'learning_rate': 0.03287208265951363, 'subsample': 0.780227309600352, 'colsample_bytree': 0.5722955564063311, 'gamma': 1.0430756990619607, 'reg_alpha': 3.345009628276054, 'reg_lambda': 4.906288239509024}. Best is trial 23 with value: 0.7213864704242209.

/tmp/ipykernel_1540/3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:29] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:29] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:29] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 10:01:30,230] Trial 25 finished with value: 0.7048275192803581 and parameters: {'n_estimators': 265, 'max_depth': 11, 'learning_rate': 0.08710624907250937, 'subsample': 0.7007284636765668, 'colsample_bytree': 0.4762706948580364, 'gamma': 0.47590463858043097, 'reg_alpha': 4.235361112460103, 'reg_lambda': 4.997067470438426}. Best is trial 23 with value: 0.7213864704242209.

/tmp/ipykernel_1540/3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:30] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:30] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:30] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/tmp/ipykernel_1540/3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:30] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 10:01:30,662] Trial 26 finished with value: 0.7023546044232417 and parameters: {'n_estimators': 177, 'max_depth': 10, 'learning_rate': 0.2838918164886904, 'subsample': 0.7649011048051568, 'colsample_bytree': 0.5471591256656997, 'gamma': 1.0012990346440567, 'reg_alpha': 2.6352484826660403, 'reg_lambda': 4.355616697492415}. Best is trial 23 with value: 0.7213864704242209.

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:30] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:31] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 10:01:31,370] Trial 27 finished with value: 0.6888665001770438 and parameters: {'n_estimators': 222, 'max_depth': 11, 'learning_rate': 0.04059880968343298, 'subsample': 0.6749887643304674, 'colsample_bytree': 0.40061483687511235, 'gamma': 2.012000322254772, 'reg_alpha': 3.7930225653819285, 'reg_lambda': 3.0879199941940207}. Best is trial 23 with value: 0.7213864704242209.

/tmp/ipykernel_1540/3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:31] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:31] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:32] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 10:01:33,043] Trial 28 finished with value: 0.6990725683698494 and parameters: {'n_estimators': 294, 'max_depth': 12, 'learning_rate': 0.020108128975951173, 'subsample': 0.8100853898446212, 'colsample_bytree': 0.5813203703483563, 'gamma': 0.4320505700333165, 'reg_alpha': 3.1660762956020947, 'reg_lambda': 2.17125442948971}. Best is trial 23 with value: 0.7213864704242209.

/tmp/ipykernel_1540/3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:33] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:33] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:33] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 10:01:33,713] Trial 29 finished with value: 0.7151398870967082 and parameters: {'n_estimators': 167, 'max_depth': 12, 'learning_rate': 0.06904715668872573, 'subsample': 0.8495535027750398, 'colsample_bytree': 0.5023670306534092, 'gamma': 0.7776845615266534, 'reg_alpha': 2.6872092787906667, 'reg_lambda': 4.3495360680659605}. Best is trial 23 with value: 0.7213864704242209.

/tmp/ipykernel_1540/3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:33] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:33] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:34] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 10:01:34,311] Trial 30 finished with value: 0.7101607280257483 and parameters: {'n_estimators': 194, 'max_depth': 8, 'learning_rate': 0.13255743358463498, 'subsample': 0.7452490250707724, 'colsample_bytree': 0.6905715884311595, 'gamma': 1.1385097028962834, 'reg_alpha': 1.1457735668872917, 'reg_lambda': 3.7963279096320535}. Best is trial 23 with value: 0.7213864704242209.

/tmp/ipykernel_1540/3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:34] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:34] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:34] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 10:01:34,988] Trial 31 finished with value: 0.7136442064073837 and parameters: {'n_estimators': 162, 'max_depth': 12, 'learning_rate': 0.0702125340229773, 'subsample': 0.8349337395484049, 'colsample_bytree': 0.49987593916233575, 'gamma': 0.7348149696113638, 'reg_alpha': 2.5804262114017615, 'reg_lambda': 4.374088709517601}. Best is trial 23 with value: 0.7213864704242209.

/tmp/ipykernel_1540/3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:35] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:35] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:35] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/tmp/ipykernel_1540/3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:35] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 10:01:35,552] Trial 32 finished with value: 0.7082477283963596 and parameters: {'n_estimators': 127, 'max_depth': 11, 'learning_rate': 0.07178249412239218, 'subsample': 0.8513904460967171, 'colsample_bytree': 0.48541122807639414, 'gamma': 0.8821510716086735, 'reg_alpha': 3.5529615445435616, 'reg_lambda': 4.6070910197768935}. Best is trial 23 with value: 0.7213864704242209.

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:35] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:35] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/tmp/ipykernel_1540/3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-07-09 10:01:36,114] Trial 33 finished with value: 0.7084513430986679 and parameters: {'n_estimators': 164, 'max_depth': 10, 'learning_rate': 0.12733339651448858, 'subsample': 0.9070336640788181, 'colsample_bytree': 0.5308093514746943, 'gamma': 0.6577834739838392, 'reg_alpha': 2.7781321701590223, 'reg_lambda': 4.257846288235197}. Best is trial 23 with value: 0.7213864704242209.

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:36] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:36] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:36] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 10:01:36,768] Trial 34 finished with value: 0.6597856442482327 and parameters: {'n_estimators': 83, 'max_depth': 12, 'learning_rate': 0.017390413878841545, 'subsample': 0.9993986750197683, 'colsample_bytree': 0.59768189243636, 'gamma': 1.1717207838013852, 'reg_alpha': 3.097412774053404, 'reg_lambda': 3.0021207980924913}. Best is trial 23 with value: 0.7213864704242209.

/tmp/ipykernel_1540/3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:36] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:37] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:37] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 10:01:37,348] Trial 35 finished with value: 0.7050208657544953 and parameters: {'n_estimators': 225, 'max_depth': 11, 'learning_rate': 0.21060158465801554, 'subsample': 0.9705707569288775, 'colsample_bytree': 0.558610477566279, 'gamma': 0.2943851808953415, 'reg_alpha': 4.077005426941609, 'reg_lambda': 4.237543462304162}. Best is trial 23 with value: 0.7213864704242209.

/tmp/ipykernel_1540/3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:37] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:37] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:37] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 10:01:38,173] Trial 36 finished with value: 0.7061904197396519 and parameters: {'n_estimators': 183, 'max_depth': 10, 'learning_rate': 0.05239606727077974, 'subsample': 0.7937110543669774, 'colsample_bytree': 0.44650274145108726, 'gamma': 0.5656996077706913, 'reg_alpha': 2.438730003693009, 'reg_lambda': 4.851399903823326}. Best is trial 23 with value: 0.7213864704242209.

/tmp/ipykernel_1540/3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:38] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:38] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:38] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 10:01:38,771] Trial 37 finished with value: 0.7064217407477149 and parameters: {'n_estimators': 256, 'max_depth': 12, 'learning_rate': 0.12492977233532984, 'subsample': 0.8931708476567854, 'colsample_bytree': 0.6204623654162498, 'gamma': 1.6200435777008275, 'reg_alpha': 2.0077550404948106, 'reg_lambda': 1.2505256929476767}. Best is trial 23 with value: 0.7213864704242209.

/tmp/ipykernel_1540/3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:38] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:39] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:39] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 10:01:39,788] Trial 38 finished with value: 0.6469084282098895 and parameters: {'n_estimators': 125, 'max_depth': 11, 'learning_rate': 0.009333656335206036, 'subsample': 0.9438994706676366, 'colsample_bytree': 0.5027074214311961, 'gamma': 3.8370761624114746, 'reg_alpha': 1.7039951037429197, 'reg_lambda': 4.575631088880745}. Best is trial 23 with value: 0.7213864704242209.

/tmp/ipykernel_1540/3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:39] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:40] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:40] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[I 2026-07-09 10:01:41,424] Trial 39 finished with value: 0.6586768230779171 and parameters: {'n_estimators': 94, 'max_depth': 8, 'learning_rate': 0.005840084866393335, 'subsample': 0.8277133000931148, 'colsample_bytree': 0.9879071628396172, 'gamma': 0.201175119020218, 'reg_alpha': 2.9426649152798126, 'reg_lambda': 3.764371885359104}. Best is trial 23 with value: 0.7213864704242209.
Best CV macro-F1: 0.7213864704242209
Best params:
  n_estimators: 182
  max_depth: 11
  learning_rate: 0.1234727012102534
  subsample: 0.7768697837788987
  colsample_bytree: 0.5706661598751535
  gamma: 1.022174195802494
  reg_alpha: 3.237402200388701
  reg_lambda: 4.947306277660575

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [10:01:41] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

FINAL Test Classification Report (class-weighted XGB):
              precision    recall  f1-score   support

        High       0.47      0.45      0.46        20
         Low       0.74      0.80      0.77        65
      Medium       0.92      0.91      0.92       315

    accuracy                           0.87       400
   macro avg       0.71      0.72      0.72       400
weighted avg       0.87      0.87      0.87       400

Confusion Matrix (rows=true, cols=pred):
[[  9   0  11]
 [  0  52  13]
 [ 10  18 287]]


#best model above one

## winner:nOptuna Tuned Class weighted XGBoost

Save the model as a .pkl file

In [59]:
import joblib

joblib.dump(model,'model_xgb_new.pkl')

print("Model saved successfully as 'model_xgb_new.pkl'")

Model saved successfully as 'model_xgb_new.pkl'